apiVersion: v1
kind: Secret
metadata:
  name: overlay-cert-injection-webhook-scantemplates
  namespace: tap-install
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay","overlay")

    #@ def cert_injection_webhook_deployment():
    kind: Deployment
    metadata:
      name: cert-injection-webhook
    #@ end

    #@overlay/match by=overlay.subset(cert_injection_webhook_deployment())
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by="name"
          - name: server
            args:
            #@overlay/append
            - -label=scantemplates.scanning.apps.tanzu.vmware.com
