apiVersion: v1
kind: Secret
metadata:
  name: tap-wildcard-cert
  namespace: kube-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFbjCCA1YCCQCz9VnyO8hNRjANBgkqhkiG9w0BAQ0FADB5MQswCQYDVQQGEwJV
    ...
    Qk4dT3Yx4hyM0+oGLQyhX2lzHsQ9xgmw=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKAIBAAKCAgEAstFu2V4ik1A011ugLmO4b+hwPzRiPnzCYTzBaVrON/XiM7w+
    ...
    Sdgtw1NmeSoeSWq5OckXjDqTdMxtbgrW+0TSSppPZYqlmOR8x5mbbLnQTso=
    -----END RSA PRIVATE KEY-----

---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: tap-wildcard-cert
  namespace: kube-system
spec:
  delegations:
    - secretName: tap-wildcard-cert
      targetNamespaces:
        - "*"